spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
      password: root
      username: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#mybatis-plus:
#  mapper-locations: classpath:com/example/retaildemo/mapper/xml/*.xml
mybatis:
  type-aliases-package: com.fengmi.fmmall.entity
  mapper-locations: classpath:mappers/*Mapper.xml

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error